---
title: "Limpieza y Merge UPAO"
author: "Cesar Poggi"
date: "2023-05-22"
output: html_document
---

Leer datos
```{r}
library(readxl)

D_E1518 <- "https://www.dropbox.com/scl/fi/m3ahgh3tech6pnoqfnrct/Data-E1518-Empleadores-EMPRESAS-2015-2018.xls?dl=1&rlkey=u6pfqbxzuyfmbuyykvvpsiypm"
destfile <- "Data_E1518_Empleadores_EMPRESAS_2015_2018.xls"
curl::curl_download(D_E1518, destfile)
E1518 <- read_excel(destfile)

D_E1819 <- "https://www.dropbox.com/scl/fi/e0jefbn1q1wh7mx0s7kb5/Data-E1819-Empleadores-EMPRESAS-2018-2019.xls?dl=1&rlkey=sxitghkcw9ig7d9j8oy229ftt"
destfile2 <- "Data_E1819_Empleadores_EMPRESAS_2018_2019.xls"
curl::curl_download(D_E1819, destfile2)
E1819 <- read_excel(destfile2)

D_E1920 <- "https://www.dropbox.com/scl/fi/k1nlcidqq7pefjo66vt80/Data-E1920-Empleadores-EMPRESAS-2019-2020.xls?dl=1&rlkey=8c9nam83vul1vp2ayk54qjngo"
destfile3 <- "Data_E1920_Empleadores_EMPRESAS_2019_2020.xls"
curl::curl_download(D_E1920, destfile3)
E1920 <- read_excel(destfile3)


D_IP1518 <- "https://www.dropbox.com/scl/fi/jn74v99xcnr7ltv1d0ry2/Data-IP1518-Empleadores-INST.PUB.-2015-2018.xls?dl=1&rlkey=hor2huo64h7x1w1n8cz3zbbte"
destfile4 <- "Data_E1518_Empleadores_INST.PUB._2015_2018.xls"
curl::curl_download(D_IP1518, destfile4)
IP1518 <- read_excel(destfile4)

D_IP1819 <- "https://www.dropbox.com/scl/fi/5hwdveoih1wz5wx5wc0zt/Data-IP1819-Empleadores-INST.PUB.-2018-2019.xls?dl=1&rlkey=y1dy3e907f7ge7anmls6fxh7j"
destfile5 <- "Data_E1819_Empleadores_INST.PUB._2018_2019.xls"
curl::curl_download(D_IP1819, destfile5)
IP1819 <- read_excel(destfile5)

D_IP1920 <- "https://www.dropbox.com/scl/fi/ytb7g4vryktru1svlk8nz/Data-IP1920-Empleadores-INST.PUB-2019-2020.xls?dl=1&rlkey=hcbvuno3kwiukgih76aswxd36"
destfile6 <- "Data_E1920_Empleadores_INST.PUB._2019_2020.xls"
curl::curl_download(D_IP1920, destfile6)
IP1920 <- read_excel(destfile6)
```

Estandarizar variables
```{r}
library(dplyr)

#Ordenar columnas
E1518 <- E1518 %>% 
    select(sort(names(.))) #con dplyr select que es para seleccionar columnas y luego usamos sort que es para ordenar un vector, que en este caso será el vector de los nombres de la variables y para eso utilizamos names
E1819 <- E1819 %>% 
    select(sort(names(.)))
E1920 <- E1920 %>% 
    select(sort(names(.)))
IP1518 <- IP1518 %>% 
    select(sort(names(.)))
IP1819 <- IP1819 %>% 
    select(sort(names(.)))
IP1920 <- IP1920 %>% 
    select(sort(names(.)))

#Cambiar nombres E
for(df in c("E1518"))
  data.table::setnames(get(df),  c("CARGO","CARRERA", "CORREO_REP", "DIRECCION", "FECHA", "RAZON_SOCIAL", "REP", "RUC", "TELF"))

for(df in c("E1819","E1920"))
  data.table::setnames(get(df),  c("ANO", "CARGO","CARRERA", "CORREO_REP", "DIRECCION", "FECHA", "RAZON_SOCIAL", "REP", "RUC", "TELF"))

#Cambiar nombres IP
for(df in c("IP1518","IP1819","IP1920"))
  data.table::setnames(get(df),  c("ANO", "CARGO","CORREO_REP", "DIRECCION","CARRERA", "FECHA", "RAZON_SOCIAL", "REP", "RUC", "TELF"))

#Crear nueva columna
E1518$ARCH <- 'E1518'
E1819$ARCH <- 'E1819'
E1920$ARCH <- 'E1920'
IP1518$ARCH <- 'IP1518'
IP1819$ARCH <- 'IP1819'
IP1920$ARCH <- 'IP1920'
```

Merge de las bases
```{r}
library(tidyverse) #tiene purr para reduce y dplyr para reduce

df_lista <- list(E1518, E1819, E1920, IP1518, IP1819, IP1920)

Empleadores_UPAO <- df_lista %>%
  reduce(full_join)
```

Organizar las columnas
```{r}
Empleadores_UPAO <- Empleadores_UPAO[,c(11,5,6,9,4,7,1,3,2,8,10)]
```



```{r}
Empleadores_UPAO <- Empleadores_UPAO %>%
  mutate(CARGO_mod =
           case_when(str_detect(CARGO, "NOTARIO") ~ 'NOTARIO',
                     
                     str_detect(CARGO, "ANALISTA") ~ 'ANALISTA',
                     
                     str_detect(CARGO, "INGENIERO") ~ 'INGENIERO',
                     
                     str_detect(CARGO, "CONTADOR") |
                       str_detect(CARGO, "CONTADORA") ~ 'CONTADOR/A',
                     
                     str_detect(CARGO, "ABOGADO") |
                       str_detect(CARGO, "ABOGADA") ~ 'ABOGADO/A',
                     
                     str_detect(CARGO, "ARQUITECTO") |
                       str_detect(CARGO, "ARQUITECTA") ~ 'ARQUITECTO/A',
                     
                     str_detect(CARGO, "GOBERNADOR") |
                       str_detect(CARGO, "GOBIERNO") ~ 'GOBIERNO',
                     
                     str_detect(CARGO, "ALCALDE") |
                       str_detect(CARGO, "ALACALDE") ~ 'ALCALDE',
                     
                     str_detect(CARGO, "ASISTENTE") ~ 'ASISTENTE',
                     
                     str_detect(CARGO, "APODERADO") |
                       str_detect(CARGO, "APODERADA") ~ 'APODERADO',
                     
                     str_detect(CARGO, "VICEPRESIDENTE") |
                       str_detect(CARGO, "VICEPRESIDENTA") ~ 'VICEPRESIDENTE',
                     
                     str_detect(CARGO, "PRESIDENTE") |
                       str_detect(CARGO, "PRESIDENTA") ~ 'PRESIDENTE/A',
                    
                     
                     str_detect(CARGO, "SUBGERENTE") |
                       str_detect(CARGO, "SUB GERENTE")|
                       str_detect(CARGO, "SU GERENTE")|
                       str_detect(CARGO, "SUB. GERENTE")|
                       str_detect(CARGO, "SUB.GERENTE")|
                       str_detect(CARGO, "SUBGERENCIA")|
                       str_detect(CARGO, "SUB GERENCIA")|
                       str_detect(CARGO, "SUB-GERENTE") ~ 'SUBGERENTE/A',
                     
                     str_detect(CARGO, "GERENTE") |
                       str_detect(CARGO, "GERENTA") |
                       str_detect(CARGO, "GETENTE") |
                       str_detect(CARGO, "GERENCIA")|
                       str_detect(CARGO, "GRRENTE") ~ 'GERENTE/GERENCIA',
                     
                     str_detect(CARGO, "GERENTE GENERAL") ~ 'GERENTE GENERAL',
                     
                     
                     str_detect(CARGO, "SUPERVISOR") |
                       str_detect(CARGO, "SUPERVISORA") ~ 'SUPERVISOR/A',
                     
                     str_detect(CARGO, "ENCARGADO") |
                       str_detect(CARGO, "ENCARGADA") ~ 'ENCARGADO/A',
                     
                     str_detect(CARGO, "SUPERINTENDENTE")|
                       str_detect(CARGO, "SUPER INTENDENTE") |
                       str_detect(CARGO, "SUPERINTENDENCIA") ~ 'SUPERINTENDENTE/A',
                     
                     
                      str_detect(CARGO, "INTENDENTE") |
                       str_detect(CARGO, "NTENDENTE") |
                       str_detect(CARGO, "INTENDENTA") |
                       str_detect(CARGO, "INTENDENCIA") ~ 'INTENDENTE/A',
                     
                     str_detect(CARGO, "SUB DIRECTOR")|
                       str_detect(CARGO, "SUB DIRECTORA") ~ 'SUBDIRECTOR/A',
                     
                     str_detect(CARGO, "DIRECTOR")|
                       str_detect(CARGO, "DIRECTORA") |
                       str_detect(CARGO, "DITECTORA") ~ 'DIRECTOR/A',
                     
                     
                     str_detect(CARGO, "MANAGER") ~ 'MANAGER',
                     
                     str_detect(CARGO, "CORONEL") ~ 'CORONEL',
                     
                     str_detect(CARGO, "COORDINADOR") |
                       str_detect(CARGO, "COORDINADORA") ~ 'COORDINADOR/A',
                     
                     str_detect(CARGO, "REPRESENTANTE") ~ 'REPRESENTANTE',
                     
                     str_detect(CARGO, "SOCIO") |
                       str_detect(CARGO, "SOCIA") ~ 'SOCIO/A',
                     
                     str_detect(CARGO, "PROMOTOR") |
                       str_detect(CARGO, "PROMOTORA") ~ 'PROMOTOR/A',
                     
                     str_detect(CARGO, "REPRESENTANTE") ~ 'REPRESENTANTE',
                     
                     str_detect(CARGO, "ASESOR") |
                       str_detect(CARGO, "ASESORA") ~ 'ASESOR/A',
                     
                     str_detect(CARGO, "SECRETARIO") |
                       str_detect(CARGO, "SECRETARIA") ~ 'SECRETARIO/A',
                     
                     str_detect(CARGO, "ADMINISTRADOR") |
                       str_detect(CARGO, "ADMINISTRADORA")|
                       str_detect(CARGO, "ADMINISTRADOR(e)") ~ 'ADMINISTRADOR/A',
                     
                     str_detect(CARGO, "RECTOR") |
                       str_detect(CARGO, "RECTORA") ~ 'RECTOR/A',
                     
                     str_detect(CARGO, "DECANO") |
                       str_detect(CARGO, "DECANA") ~ 'DECANO/A',
                     
                     str_detect(CARGO, "JEFE") |
                       str_detect(CARGO, "JEFA") |
                       str_detect(CARGO, "JEFE(E)") |
                       str_detect(CARGO, "JEFE(e)") |
                       str_detect(CARGO, "JEFATURA")|
                       str_detect(CARGO, "GEFE") ~ 'JEFE/A'))
```


```{r}
Empleadores_UPAO$CARGO_mod <- Empleadores_UPAO$CARGO_mod %>%
  replace_na('OTROS')

Empleadores_UPAO$REP_mod=substr(Empleadores_UPAO$REP, 1,4)
```


Eliminar casos repetidos, teniendo en cuenta la fecha
```{r}
#Cambiamos la variable fecha a formato fecha
Empleadores_UPAO$FECHA <- as.Date(Empleadores_UPAO$FECHA, '%d/%m/%Y')

library(dplyr)

Empleadores_UPAO_GG <- Empleadores_UPAO %>%  # Order data using dplyr package
  arrange(RUC, desc(FECHA)) %>%
  filter(!duplicated(cbind(RUC, CARGO_mod)))

Empleadores_UPAO_FF <- Empleadores_UPAO_GG %>%  # Order data using dplyr package
  arrange(RUC, desc(FECHA)) %>%
  filter(!duplicated(cbind(RUC, REP_mod)))

#Tabla=aggregate(ANO ~ RUC, data=Empleadores_UPAO_FF, length)
```

Guardemos la base
```{r}
Empleadores_UPAO_FF <- Empleadores_UPAO_FF %>%  # Order data using dplyr package
  arrange(desc(FECHA))

library(lubridate)
Empleadores_UPAO_FF$ANO <- year(Empleadores_UPAO_FF$FECHA)

Empleadores_UPAO_FF <- Empleadores_UPAO_FF[,c(1,2,3,5,10,6,13,7,12,8,4,9,11)]

library("writexl")  
write_xlsx(Empleadores_UPAO_FF,"C:\\Users\\Alejandro\\Documents\\Empleadores_UPAO_V4.xlsx")
```

